version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # volumes:
    #   - ./esdata:/usr/share/elasticsearch/data
    #   - ./config:/usr/share/elasticsearch/config
    #   - ./plugins:/usr/share/elasticsearch/plugins
    ports:
      - 9200:9200
      - 9300:9300